services:
  db:
    image: mysql:8.4.0
    container_name: mysql-8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
      MYSQL_USER: app_user
      MYSQL_PASSWORD: omsairam
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - application
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.local
    x-bake:
      platform: linux/amd64
      provenance: false
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: products
      PORT: 5001
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5001:5001'
    networks:
      - application

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.local
    x-bake:
      platform: linux/amd64
      provenance: false
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: 'http://localhost:5001'
    ports:
      - '3000:3000'
    networks:
      - application

volumes:
  mysql_data:

networks:
  application:
    driver: bridge
